version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizzy_backend_mongo
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
      - "${WEB_SOCKET_SERVER_PORT}:3003"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:7
    container_name: quizzy_database_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_quizzy:/data/db

volumes:
  mongo_quizzy:
